public class Clima{
    String ano; //2024, 2025, 2026...
    String mes; //Janeiro, Fevereiro, Março...     
    String temperatura; //Frio(até 15°C), Ameno(16°C à 25°C), Quente(Acima de 25°C)
    int precipitacao; // Nada, pouco(Até 20mm), média(De 21mm à 40mm), Alta(Acima de 40mm)...
}
